version: "3"
services:
  app:
    build: ./docker/app
    volumes:
      - ../:/workspace:cached
    ports:
      - 80:80
    tty: true
    environment:
        APP_ENV: local
        PHP_EXTENSION_XDEBUG: 1
        PHP_EXTENSION_MYSQL: 1
        PHP_EXTENSION_PDO_MYSQL: 1
        APACHE_DOCUMENT_ROOT: /workspace/public
  db:
    image: mysql:8.0.36
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      #MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    ports:
      -   "80:80"
    environment:
      #PMA_HOST: laravel_eleven_app_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025